# Generated by Django 3.0.5 on 2020-08-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaleApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.SmallIntegerField(default=1)),
                ('question', models.CharField(max_length=800)),
                ('answer', models.CharField(choices=[('0', 'কখনোই না'), ('1', 'অনেকাংশে না'), ('2', 'মাঝে মাঝে'), ('3', 'প্রায়শই'), ('4', 'ঘনঘন')], default=None, max_length=15)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('scale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scaleApp.MeasuringScale')),
            ],
        ),
    ]
