# Generated by Django 3.0.5 on 2020-08-12 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaleApp', '0002_questiondetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondetails',
            name='answer',
        ),
        migrations.CreateModel(
            name='AnswerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=30)),
                ('serial', models.SmallIntegerField(default=1)),
                ('value', models.SmallIntegerField(default=1)),
                ('scale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scaleApp.MeasuringScale')),
            ],
        ),
    ]
