# Generated by Django 3.0.5 on 2020-08-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaleApp', '0003_auto_20200812_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.SmallIntegerField(default=0)),
                ('to_value', models.SmallIntegerField(default=0)),
                ('result', models.SmallIntegerField(default=1)),
                ('scale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scaleApp.MeasuringScale')),
            ],
        ),
    ]
