# -*- coding: utf-8 -*-
"""Copy of keras-ocr.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAQlJi14n1ZxjrHPeypMbLqFf_dxQUTw

Documentation:
https://keras-ocr.readthedocs.io/en/latest/

Based on: https://github.com/clovaai/CRAFT-pytorch
"""

!pip install keras-ocr

import keras_ocr
from matplotlib import pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

# keras-ocr will automatically download pretrained
# weights for the detector and recognizer.
pipeline = keras_ocr.pipeline.Pipeline()

# List of three example images
images = [keras_ocr.tools.read(img) for img in ['/content/drive/MyDrive/Colab Notebooks/ocr_test/6.jpg',
                                               '/content/drive/MyDrive/Colab Notebooks/ocr_test/5.jpg',
                                               ]
]

#Print shape...
import numpy as np
print("ok")

detector = keras_ocr.detection.Detector()
images = [
            keras_ocr.tools.resize_image(image, max_scale=2, max_size=2048)
            for image in images
        ]
max_height, max_width = np.array([image.shape[:2] for image, scale in images]).max(axis=0)
scales = [scale for _, scale in images]
images = np.array(
            [keras_ocr.tools.pad(image, width=max_width, height=max_height) for image, _ in images])
prediction_groups = detector.detect(images=images)

show_img = plt.imshow(images[0])
for card in prediction_groups:
  fig, axs = plt.subplots(nrows=len(card), figsize=(20, 20))
  for ax, box in zip(axs,card):
    img = keras_ocr.tools.warpBox(image=images[0], box=box)
    show_img = plt.imshow(img)

# Each list of predictions in prediction_groups is a list of
# (word, box) tuples.
prediction_groups = pipeline.recognize(images)
#print(prediction_groups)
print()

# Plot the predictions
fig, axs = plt.subplots(nrows=len(images), figsize=(20, 20))
for ax, image, predictions in zip(axs, images, prediction_groups):
    keras_ocr.tools.drawAnnotations(image=image, predictions=predictions, ax=ax)

"""# New Section"""