# Generated by Django 3.0.5 on 2020-08-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructorApp', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, default='default', upload_to='image/courseImage')),
                ('featured_video', models.URLField()),
                ('requirement', models.CharField(max_length=500)),
                ('pre_requisite', models.CharField(max_length=500)),
                ('what_u_will_learn', models.TextField()),
                ('course_hours', models.TimeField()),
                ('course_Lectures', models.IntegerField()),
                ('total_student_enrolled', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('course', models.ManyToManyField(to='courseApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseApp.CourseLevel')),
            ],
        ),
        migrations.CreateModel(
            name='PathCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseApp.Course')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseApp.LearningPath')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('video', models.URLField(max_length=300)),
                ('description', models.TextField(max_length=10000)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('module_id', models.ManyToManyField(to='courseApp.CourseModule')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ManyToManyField(to='courseApp.Course')),
                ('instructor_id', models.ManyToManyField(to='instructorApp.Instructor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_lang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseApp.Language'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ManyToManyField(to='instructorApp.Instructor'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courseApp.CourseLevel'),
        ),
        migrations.CreateModel(
            name='AnalyzeLevelMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=500)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('module_id', models.ManyToManyField(to='courseApp.CourseModule')),
            ],
        ),
    ]
