# Generated by Django 3.0.5 on 2020-08-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0004_auto_20200814_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='featured_video',
            field=models.CharField(max_length=400),
        ),
    ]
