# Generated by Django 3.0.5 on 2020-08-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0002_auto_20200817_0116'),
        ('courseApp', '0006_remove_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinstructor',
            name='course_id',
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseApp.Course'),
        ),
        migrations.RemoveField(
            model_name='courseinstructor',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='courseinstructor',
            name='instructor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instructorApp.Instructor'),
        ),
    ]
