# Generated by Django 3.0.5 on 2020-08-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0007_auto_20200817_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='course',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseApp.Course'),
            preserve_default=False,
        ),
    ]
