# Generated by Django 3.0.5 on 2020-08-09 19:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructorApp', '0001_initial'),
        ('courseApp', '0001_initial'),
        ('paymentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolment_status', models.CharField(choices=[('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('ongoing', 'ONGOING'), ('notStarted', 'NOTSTARTED')], default='bkash', max_length=10)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('course_id', models.ManyToManyField(to='courseApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField()),
                ('details', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default', upload_to='image/pro_pics')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructorApp.Country')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentWorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='EnrolledModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_module_on', models.DateField(auto_now_add=True)),
                ('last_visited_on', models.DateField(auto_now=True)),
                ('enrolled_id', models.ManyToManyField(to='studentApp.EnrolledCourse')),
                ('module_id', models.ManyToManyField(to='courseApp.CourseModule')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paymentApp.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='enrolledcourse',
            name='student_id',
            field=models.ManyToManyField(to='studentApp.Student'),
        ),
    ]
