# Generated by Django 3.0.5 on 2020-08-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='details',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
