# Generated by Django 3.0.5 on 2020-08-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_auto_20200810_2345'),
        ('scaleApp', '0001_initial'),
        ('studentApp', '0002_auto_20200810_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringScaleForModuleResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalMarks', models.PositiveSmallIntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.CourseModule')),
                ('scale_name', models.ManyToManyField(to='scaleApp.MeasuringScale')),
            ],
        ),
    ]
