# Generated by Django 3.0.5 on 2020-08-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_measuringscaleformoduleresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringscaleformoduleresult',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentApp.Student'),
            preserve_default=False,
        ),
    ]
