# Generated by Django 3.0.5 on 2020-08-13 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_auto_20200810_2345'),
        ('studentApp', '0004_measuringscaleformoduleresult_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringscaleformoduleresult',
            name='module_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='courseApp.CourseModule'),
        ),
    ]
