# Generated by Django 3.0.5 on 2020-08-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0005_auto_20200813_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuringscaleformoduleresult',
            name='module_id',
        ),
    ]
