# Generated by Django 3.0.5 on 2020-08-13 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaleApp', '0005_auto_20200813_1952'),
        ('studentApp', '0006_remove_measuringscaleformoduleresult_module_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measuringscaleformoduleresult',
            name='scale_name',
        ),
        migrations.AddField(
            model_name='measuringscaleformoduleresult',
            name='scale_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scaleApp.MeasuringScale'),
            preserve_default=False,
        ),
    ]
