# Generated by Django 3.0.5 on 2020-06-11 03:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructorApp', '0001_initial'),
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField(default=None)),
                ('to_time', models.TimeField(default=None)),
                ('day', models.CharField(choices=[('saturday', 'SATURDAY'), ('sunday', 'SUNDAY'), ('monday', 'MONDAY'), ('tuesday', 'TUESDAY'), ('wednesday', 'WEDNESDAY'), ('thursday', 'THURSDAY'), ('Friday', 'FRIDAY')], default='saturday', max_length=9)),
                ('counselor', models.ManyToManyField(to='instructorApp.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=datetime.datetime.today)),
                ('note', models.CharField(max_length=150)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentApp.Student')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointmentApp.SlotList')),
            ],
        ),
    ]
