# Generated by Django 3.0.5 on 2020-08-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('content', 'Content'), ('scale', 'Scale')], default='content', max_length=8),
        ),
    ]
