# Generated by Django 3.0.5 on 2020-08-19 12:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0002_lesson_lesson_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_hours',
        ),
        migrations.AddField(
            model_name='course',
            name='what_u_will_learn',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='total_student_enrolled',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enrolledcourse',
            name='enrolment_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('notStarted', 'NOTSTARTED')], default='notStarted', max_length=11),
        ),
        migrations.AlterField(
            model_name='enrolledmodule',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.CourseModule'),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='module_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.CourseModule'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='measuringscaleformodule',
            name='module_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.CourseModule'),
        ),
        migrations.CreateModel(
            name='EnrolledLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_status', models.CharField(choices=[('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('notStarted', 'NOTSTARTED')], default='notStarted', max_length=11)),
                ('enrolled_module_on', models.DateField(auto_now_add=True)),
                ('last_visited_on', models.DateField(auto_now=True)),
                ('enrolled_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.EnrolledCourse')),
                ('lesson_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eduvateApp.Lesson')),
            ],
        ),
    ]
