# Generated by Django 3.0.5 on 2020-08-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0006_auto_20200820_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedlesson',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
