# Generated by Django 3.0.5 on 2020-08-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0007_completedlesson_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledmodule',
            name='enrolled_id',
        ),
        migrations.AddField(
            model_name='enrolledmodule',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.Student'),
        ),
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_course_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eduvateApp.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.Student')),
            ],
        ),
    ]
