# Generated by Django 3.0.5 on 2020-08-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0008_auto_20200820_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledmodule',
            name='enrolment_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('partial', 'PARTIAL'), ('notStarted', 'NOTSTARTED')], default='notStarted', max_length=11),
        ),
    ]
