# Generated by Django 3.0.5 on 2020-08-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0009_enrolledmodule_enrolment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='percent_complited',
            field=models.SmallIntegerField(null=True),
        ),
    ]
