# Generated by Django 3.0.5 on 2020-08-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0010_enrolledcourse_percent_complited'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcourse',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
