# Generated by Django 3.0.5 on 2020-08-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0012_auto_20200821_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonscale',
            name='lesson_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.Lesson'),
        ),
    ]
