# Generated by Django 3.0.5 on 2020-08-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0014_measuringscaleformoduleresult_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, max_length=400, null=True)),
                ('field_2', models.CharField(blank=True, max_length=400, null=True)),
                ('field_3', models.CharField(blank=True, max_length=400, null=True)),
                ('field_4', models.CharField(blank=True, max_length=400, null=True)),
                ('field_5', models.CharField(blank=True, max_length=400, null=True)),
                ('field_6', models.CharField(blank=True, max_length=400, null=True)),
                ('complete_course_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='eduvateApp.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduvateApp.Student')),
            ],
        ),
    ]
