# Generated by Django 3.0.5 on 2020-08-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0015_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='field_1',
            new_name='bad_comment',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='field_2',
            new_name='good_comment',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='field_3',
            new_name='opinion',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='field_4',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='field_5',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='field_6',
        ),
        migrations.AddField(
            model_name='feedback',
            name='Quality',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='satisfaction',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
