# Generated by Django 3.0.5 on 2020-08-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0016_auto_20200822_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Quality',
            new_name='quality',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('content', 'Content'), ('scale', 'Scale'), ('feedback', 'Feedback Form')], default='content', max_length=8),
        ),
    ]
