# Generated by Django 3.0.5 on 2020-08-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0017_auto_20200823_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringscaleformoduleresult',
            name='result',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
