# Generated by Django 3.0.5 on 2020-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0019_lessonfeedbackcollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='complete_course_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lessonfeedbackcollection',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
