# Generated by Django 3.0.5 on 2021-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0021_auto_20201125_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_name', models.CharField(max_length=200)),
                ('template_name', models.CharField(max_length=249)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('content', 'Content'), ('contform', 'Form inside content'), ('scale', 'Scale'), ('feedback', 'Feedback Form')], default='content', max_length=8),
        ),
        migrations.AddField(
            model_name='lesson',
            name='homework_list',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='eduvateApp.HomeworkTemplate'),
        ),
    ]
