# Generated by Django 3.0.5 on 2021-05-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduvateApp', '0022_auto_20210507_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework_list',
            field=models.ManyToManyField(blank=True, default=None, to='eduvateApp.HomeworkTemplate'),
        ),
    ]
