# Generated by Django 3.0.5 on 2020-08-09 19:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=250)),
                ('city', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, default='default', upload_to='image/pro_pics')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instructorApp.Country')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorWorkHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructorApp.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_count', models.PositiveSmallIntegerField(default=0)),
                ('rating_total_value', models.PositiveIntegerField(default=0)),
                ('instructor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instructorApp.Instructor')),
            ],
        ),
    ]
