# Generated by Django 3.0.5 on 2020-08-16 19:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='fb_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
