# Generated by Django 3.0.5 on 2020-06-11 04:57

from django.db import migrations
import instructorApp.managers


class Migration(migrations.Migration):

    dependencies = [
        ('instructorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', instructorApp.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
